# Generated by Django 3.2.5 on 2021-08-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=222, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='relation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
